/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter/index.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader/index.vue')['default']
    AppMain: typeof import('./src/components/AppMain/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    HeaderSearch: typeof import('./src/components/HeaderSearch/index.vue')['default']
    Link: typeof import('./src/components/Sidebar/Link.vue')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./src/components/Screenfull/index.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./src/components/Sidebar/SidebarItem.vue')['default']
    SizeSelect: typeof import('./src/components/SizeSelect/index.vue')['default']
  }
}
